- name: Create RMON Agent directory
  file:
    path: "{{ item }}"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    state: directory
  with_items:  ["/etc/rmon", "/var/lib/rmon", "/var/lib/rmon/rmon-agent", "/var/log/rmon"]
  ignore_errors: yes

- name: Copy RMON Agent files
  ansible.builtin.copy:
    src: "/var/www/rmon/app/tools/rmon-agent/{{ item }}"
    dest: "/var/lib/rmon/rmon-agent/{{ item }}"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0644'
  with_items: ["rmon_agent.py", "rmon_agent_common.py", "rmon_checks.py", "wsgi.py", "requirements.txt"]

- name: Copy RMON Agent service file
  template:
    src: "{{ item.file }}"
    dest: "{{ item.path }}"
    mode: 0644
  with_items:
    - {file: "rmon-agent.service.j2", path: "/etc/systemd/system/rmon-agent.service"}
    - {file: "logrotate.j2", path: "/etc/logrotate.d/rmon-agent"}
    - {file: "rsyslog.conf.j2", path: "/etc/rsyslog.d/rmon-agent.conf"}
  notify:
    - Restart rsyslog
    - Restart RMON agent

- name: Install requirements
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/install-{{ ansible_facts['os_family'] | lower }}.yml"

- name: Copy RMON Agent config file
  template:
    src: rmon-agent.cfg.j2
    dest: /etc/rmon/rmon-agent.cfg
    mode: 0644
  notify:
    - Restart RMON agent

- name: Start and enable RMON Agent
  ansible.builtin.systemd:
    name: rmon-agent
    enabled: true
    masked: no
    daemon_reload: true
    state: started
