- name: Install EPEL
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: Upgrade pip3
  pip:
    name: pip
    executable: pip3
    state: latest
    extra_args: --upgrade

- name: Install RMON Agent python requirements
  ansible.builtin.pip:
    requirements: /var/lib/rmon/rmon-agent/requirements.txt
